//// mock API for a sample Grixis Midrange decklist (API access on other sites requires premium subscription)
export const grixisMidrange = [
    "Bloodtithe Harvester",
    "Bloodtithe Harvester",
    "Bloodtithe Harvester",
    "Bloodtithe Harvester",
    "Corpse Appraiser",
    "Corpse Appraiser",
    "Corpse Appraiser",
    "Corpse Appraiser",
    "Sheoldred, The Apocalypse",
    "Sheoldred, The Apocalypse",
    "Sheoldred, The Apocalypse",
    "Make Disappear",
    "Make Disappear",
    "Make Disappear",
    "Infernal Grasp",
    "Infernal Grasp",
    "Infernal Grasp",
    "Infernal Grasp",
    "Abrade",
    "Abrade",
    "Duress",
    "Duress",
    "Invoke Despair",
    "Invoke Despair",
    "Invoke Despair",
    "Invoke Despair",
    "Reckoner Bankbuster",
    "Reckoner Bankbuster",
    "Reckoner Bankbuster",
    "Reckoner Bankbuster",
    "Fable Of The Mirror-Breaker",
    "Fable Of The Mirror-Breaker",
    "Fable Of The Mirror-Breaker",
    "Fable Of The Mirror-Breaker",
    "Swamp",
    "Swamp",
    "Swamp",
    "Swamp",
    "Shivan Reef",
    "Shivan Reef",
    "Shivan Reef",
    "Shivan Reef",
    "Sulfurous Springs",
    "Sulfurous Springs",
    "Sulfurous Springs",
    "Sulfurous Springs",
    "Haunted Ridge",
    "Haunted Ridge",
    "Haunted Ridge",
    "Haunted Ridge",
    "Shipwreck Marsh",
    "Shipwreck Marsh",
    "Shipwreck Marsh",
    "Shipwreck Marsh",
    "Xander's Lounge",
    "Xander's Lounge",
    "Xander's Lounge",
    "Xander's Lounge",
    "Takenuma, Abandoned Mire",
    "Takenuma, Abandoned Mire",
];
